- hosts: localhost
  connection: local
  gather_facts: no           
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
      - caskroom/versions
    homebrew_packages:
      - { name: ansible }
      - { name: curl }
      - { name: git }
      - { name: jq }
      - { name: lv }
      - { name: nkf }
      - { name: python }
      - { name: rbenv }
      - { name: ruby-build }
      - { name: tmux }
      - { name: tree }
      - { name: wget }
      - { name: zsh, install_options: disable-etcdir }
    homebrew_cask_packages:
      - { name: appcleaner }
      - { name: atom }
      - { name: bathyscaphe }
      - { name: bettertouchtool }
      - { name: cheatsheet }
      - { name: dash }
      - { name: day-o }
      - { name: dropbox }
      - { name: firefox-ja }
      - { name: flux }
      - { name: gitx }
      - { name: graphviz }
      - { name: google-japanese-ime }
      - { name: gyazo }
      - { name: hyperswitch }
      - { name: karabiner }
      - { name: kindle }
      - { name: macvim-kaoriya }
      - { name: pandoc }
      - { name: skype }
      - { name: sourcetree }
      - { name: spectacle }
      - { name: virtualbox }

  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    # brew
    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages

    # cask
    - name: homebrew-cask のインストール
      homebrew: name=brew-cask state=latest
    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages

    # oh-my-zsh
    - name: oh-my-zsh のインストール
      shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
      args:
        creates: ~/.oh-my-zsh/
